services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: predictor_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV=development
      - PYTHONPATH=/app
    volumes:
      - ./backend/app:/app/app:ro
      - ./models_bin:/models_bin:ro
      - ./dataset:/app/dataset
    networks:
      - predictor-net

  data-scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: predictor_scheduler
    restart: unless-stopped
    command: python scripts/get_last_date.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      - ./backend/app:/app/app:ro
      - ./backend/scripts:/app/scripts:ro
      - ./dataset:/app/dataset
    # volumes:
    #   # Montera app-koden så att ändringar i schemaläggaren slår igenom utan rebuild
    #   - ./backend/app:/app/app:ro
    #   - ./backend/scripts:/app/scripts:ro
    #   # Samma dataset-mapp så schedulern skriver direkt till din lokala mapp
    #   - ./dataset:/app/dataset
    networks:
      - predictor-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: predictor_ui
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - predictor-net

networks:
  predictor-net:
    driver: bridge
