import type { WeatherDay } from "../types/Weather";

export const mockWeather: WeatherDay[] = [
  {
    date: "2026-09-17",
    dayName: "Idag",
    weatherType: "clear",
    temperatureMax: 18,
    temperatureMin: 11,
    precipitationMm: 0,
    windSpeedKmh: 12,
  },
  {
    date: "2026-09-18",
    dayName: "Fre",
    weatherType: "rain",
    temperatureMax: 16,
    temperatureMin: 10,
    precipitationMm: 4.2,
    windSpeedKmh: 18,
  },
  {
    date: "2026-09-19",
    dayName: "Lör",
    weatherType: "cloudy",
    temperatureMax: 15,
    temperatureMin: 9,
    precipitationMm: 1.1,
    windSpeedKmh: 15,
  },
  {
    date: "2026-09-20",
    dayName: "Sön",
    weatherType: "partlyCloudy",
    temperatureMax: 19,
    temperatureMin: 12,
    precipitationMm: 0.3,
    windSpeedKmh: 9,
  },
  {
    date: "2026-09-21",
    dayName: "Mån",
    weatherType: "heavyRain",
    temperatureMax: 14,
    temperatureMin: 9,
    precipitationMm: 12.5,
    windSpeedKmh: 24,
  },
  {
    date: "2026-09-22",
    dayName: "Tis",
    weatherType: "clear",
    temperatureMax: 17,
    temperatureMin: 10,
    precipitationMm: 0,
    windSpeedKmh: 8,
  },
  {
    date: "2026-09-23",
    dayName: "Ons",
    weatherType: "partlyCloudy",
    temperatureMax: 20,
    temperatureMin: 13,
    precipitationMm: 0.6,
    windSpeedKmh: 11,
  },
];