
import type { WeatherDay } from "../types/Weather";

export const mockWeather: WeatherDay[] = [
  {
    date: "2026-09-17",
    dayName: "Idag",
    weatherType: "clear",
    temperatureMax: 18,
    temperatureMin: 11,
    precipitationMm: 0,
    windSpeedKmh: 12,
    hourlyForecast: [
      {
        time: "00:00",
        temperature: 12,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "01:00",
        temperature: 12,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "02:00",
        temperature: 11,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "clear",
      },
      {
        time: "03:00",
        temperature: 11,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "clear",
      },
      {
        time: "04:00",
        temperature: 11,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "clear",
      },
      {
        time: "05:00",
        temperature: 11,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "06:00",
        temperature: 12,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "clear",
      },
      {
        time: "07:00",
        temperature: 13,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "clear",
      },
      {
        time: "08:00",
        temperature: 14,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 11,
        weatherType: "clear",
      },
      {
        time: "09:00",
        temperature: 15,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 12,
        weatherType: "clear",
      },
      {
        time: "10:00",
        temperature: 16,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 12,
        weatherType: "clear",
      },
      {
        time: "11:00",
        temperature: 17,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 13,
        weatherType: "clear",
      },
      {
        time: "12:00",
        temperature: 18,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 13,
        weatherType: "clear",
      },
      {
        time: "13:00",
        temperature: 18,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 14,
        weatherType: "clear",
      },
      {
        time: "14:00",
        temperature: 18,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 14,
        weatherType: "clear",
      },
      {
        time: "15:00",
        temperature: 17,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 13,
        weatherType: "clear",
      },
      {
        time: "16:00",
        temperature: 17,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 12,
        weatherType: "clear",
      },
      {
        time: "17:00",
        temperature: 16,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 11,
        weatherType: "clear",
      },
      {
        time: "18:00",
        temperature: 15,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "clear",
      },
      {
        time: "19:00",
        temperature: 14,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "clear",
      },
      {
        time: "20:00",
        temperature: 13,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "clear",
      },
      {
        time: "21:00",
        temperature: 13,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "22:00",
        temperature: 12,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "23:00",
        temperature: 12,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
    ],
  },

  {
    date: "2026-09-18",
    dayName: "Fre",
    weatherType: "rain",
    temperatureMax: 16,
    temperatureMin: 10,
    precipitationMm: 4.2,
    windSpeedKmh: 18,
    hourlyForecast: [
      {
        time: "00:00",
        temperature: 12,
        precipitationProbability: 30,
        precipitationMm: 0,
        windSpeedKmh: 14,
        weatherType: "cloudy",
      },
      {
        time: "01:00",
        temperature: 12,
        precipitationProbability: 35,
        precipitationMm: 0,
        windSpeedKmh: 14,
        weatherType: "cloudy",
      },
      {
        time: "02:00",
        temperature: 11,
        precipitationProbability: 40,
        precipitationMm: 0.1,
        windSpeedKmh: 15,
        weatherType: "rain",
      },
      {
        time: "03:00",
        temperature: 11,
        precipitationProbability: 50,
        precipitationMm: 0.2,
        windSpeedKmh: 15,
        weatherType: "rain",
      },
      {
        time: "04:00",
        temperature: 11,
        precipitationProbability: 60,
        precipitationMm: 0.3,
        windSpeedKmh: 16,
        weatherType: "rain",
      },
      {
        time: "05:00",
        temperature: 10,
        precipitationProbability: 65,
        precipitationMm: 0.4,
        windSpeedKmh: 16,
        weatherType: "rain",
      },
      {
        time: "06:00",
        temperature: 10,
        precipitationProbability: 70,
        precipitationMm: 0.5,
        windSpeedKmh: 17,
        weatherType: "rain",
      },
      {
        time: "07:00",
        temperature: 11,
        precipitationProbability: 75,
        precipitationMm: 0.5,
        windSpeedKmh: 17,
        weatherType: "rain",
      },
      {
        time: "08:00",
        temperature: 12,
        precipitationProbability: 70,
        precipitationMm: 0.4,
        windSpeedKmh: 18,
        weatherType: "rain",
      },
      {
        time: "09:00",
        temperature: 13,
        precipitationProbability: 65,
        precipitationMm: 0.3,
        windSpeedKmh: 18,
        weatherType: "rain",
      },
      {
        time: "10:00",
        temperature: 14,
        precipitationProbability: 60,
        precipitationMm: 0.3,
        windSpeedKmh: 18,
        weatherType: "rain",
      },
      {
        time: "11:00",
        temperature: 15,
        precipitationProbability: 55,
        precipitationMm: 0.2,
        windSpeedKmh: 19,
        weatherType: "rain",
      },
      {
        time: "12:00",
        temperature: 16,
        precipitationProbability: 50,
        precipitationMm: 0.2,
        windSpeedKmh: 19,
        weatherType: "rain",
      },
      {
        time: "13:00",
        temperature: 16,
        precipitationProbability: 45,
        precipitationMm: 0.1,
        windSpeedKmh: 18,
        weatherType: "cloudy",
      },
      {
        time: "14:00",
        temperature: 16,
        precipitationProbability: 40,
        precipitationMm: 0.1,
        windSpeedKmh: 18,
        weatherType: "cloudy",
      },
      {
        time: "15:00",
        temperature: 15,
        precipitationProbability: 35,
        precipitationMm: 0,
        windSpeedKmh: 17,
        weatherType: "cloudy",
      },
      {
        time: "16:00",
        temperature: 15,
        precipitationProbability: 30,
        precipitationMm: 0,
        windSpeedKmh: 17,
        weatherType: "cloudy",
      },
      {
        time: "17:00",
        temperature: 14,
        precipitationProbability: 30,
        precipitationMm: 0,
        windSpeedKmh: 16,
        weatherType: "cloudy",
      },
      {
        time: "18:00",
        temperature: 14,
        precipitationProbability: 25,
        precipitationMm: 0,
        windSpeedKmh: 15,
        weatherType: "partlyCloudy",
      },
      {
        time: "19:00",
        temperature: 13,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 14,
        weatherType: "partlyCloudy",
      },
      {
        time: "20:00",
        temperature: 12,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 14,
        weatherType: "cloudy",
      },
      {
        time: "21:00",
        temperature: 12,
        precipitationProbability: 25,
        precipitationMm: 0,
        windSpeedKmh: 13,
        weatherType: "cloudy",
      },
      {
        time: "22:00",
        temperature: 11,
        precipitationProbability: 25,
        precipitationMm: 0,
        windSpeedKmh: 13,
        weatherType: "cloudy",
      },
      {
        time: "23:00",
        temperature: 11,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 12,
        weatherType: "cloudy",
      },
    ],
  },

  {
    date: "2026-09-19",
    dayName: "Lör",
    weatherType: "cloudy",
    temperatureMax: 15,
    temperatureMin: 9,
    precipitationMm: 1.1,
    windSpeedKmh: 15,
    hourlyForecast: [
      {
        time: "00:00",
        temperature: 10,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 12,
        weatherType: "cloudy",
      },
      {
        time: "01:00",
        temperature: 10,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 12,
        weatherType: "cloudy",
      },
      {
        time: "02:00",
        temperature: 9,
        precipitationProbability: 25,
        precipitationMm: 0.1,
        windSpeedKmh: 11,
        weatherType: "cloudy",
      },
      {
        time: "03:00",
        temperature: 9,
        precipitationProbability: 30,
        precipitationMm: 0.1,
        windSpeedKmh: 11,
        weatherType: "rain",
      },
      {
        time: "04:00",
        temperature: 9,
        precipitationProbability: 35,
        precipitationMm: 0.1,
        windSpeedKmh: 11,
        weatherType: "rain",
      },
      {
        time: "05:00",
        temperature: 9,
        precipitationProbability: 40,
        precipitationMm: 0.2,
        windSpeedKmh: 12,
        weatherType: "rain",
      },
      {
        time: "06:00",
        temperature: 10,
        precipitationProbability: 45,
        precipitationMm: 0.2,
        windSpeedKmh: 13,
        weatherType: "rain",
      },
      {
        time: "07:00",
        temperature: 10,
        precipitationProbability: 40,
        precipitationMm: 0.1,
        windSpeedKmh: 14,
        weatherType: "cloudy",
      },
      {
        time: "08:00",
        temperature: 11,
        precipitationProbability: 35,
        precipitationMm: 0.1,
        windSpeedKmh: 14,
        weatherType: "cloudy",
      },
      {
        time: "09:00",
        temperature: 12,
        precipitationProbability: 30,
        precipitationMm: 0,
        windSpeedKmh: 15,
        weatherType: "cloudy",
      },
      {
        time: "10:00",
        temperature: 13,
        precipitationProbability: 25,
        precipitationMm: 0,
        windSpeedKmh: 15,
        weatherType: "cloudy",
      },
      {
        time: "11:00",
        temperature: 14,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 15,
        weatherType: "cloudy",
      },
      {
        time: "12:00",
        temperature: 15,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 16,
        weatherType: "partlyCloudy",
      },
      {
        time: "13:00",
        temperature: 15,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 16,
        weatherType: "partlyCloudy",
      },
      {
        time: "14:00",
        temperature: 15,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 15,
        weatherType: "partlyCloudy",
      },
      {
        time: "15:00",
        temperature: 14,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 15,
        weatherType: "partlyCloudy",
      },
      {
        time: "16:00",
        temperature: 14,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 14,
        weatherType: "cloudy",
      },
      {
        time: "17:00",
        temperature: 13,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 13,
        weatherType: "cloudy",
      },
      {
        time: "18:00",
        temperature: 12,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 12,
        weatherType: "cloudy",
      },
      {
        time: "19:00",
        temperature: 12,
        precipitationProbability: 25,
        precipitationMm: 0.1,
        windSpeedKmh: 12,
        weatherType: "cloudy",
      },
      {
        time: "20:00",
        temperature: 11,
        precipitationProbability: 25,
        precipitationMm: 0.1,
        windSpeedKmh: 11,
        weatherType: "cloudy",
      },
      {
        time: "21:00",
        temperature: 11,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 11,
        weatherType: "cloudy",
      },
      {
        time: "22:00",
        temperature: 10,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "cloudy",
      },
      {
        time: "23:00",
        temperature: 10,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "cloudy",
      },
    ],
  },

  {
    date: "2026-09-20",
    dayName: "Sön",
    weatherType: "partlyCloudy",
    temperatureMax: 19,
    temperatureMin: 12,
    precipitationMm: 0.3,
    windSpeedKmh: 9,
    hourlyForecast: [
      {
        time: "00:00",
        temperature: 13,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
      {
        time: "01:00",
        temperature: 13,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
      {
        time: "02:00",
        temperature: 12,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "cloudy",
      },
      {
        time: "03:00",
        temperature: 12,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "cloudy",
      },
      {
        time: "04:00",
        temperature: 12,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "cloudy",
      },
      {
        time: "05:00",
        temperature: 12,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "cloudy",
      },
      {
        time: "06:00",
        temperature: 13,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "partlyCloudy",
      },
      {
        time: "07:00",
        temperature: 14,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
      {
        time: "08:00",
        temperature: 15,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
      {
        time: "09:00",
        temperature: 16,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
      {
        time: "10:00",
        temperature: 17,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "clear",
      },
      {
        time: "11:00",
        temperature: 18,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "clear",
      },
      {
        time: "12:00",
        temperature: 19,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "clear",
      },
      {
        time: "13:00",
        temperature: 19,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "clear",
      },
      {
        time: "14:00",
        temperature: 19,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "partlyCloudy",
      },
      {
        time: "15:00",
        temperature: 18,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "partlyCloudy",
      },
      {
        time: "16:00",
        temperature: 18,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "partlyCloudy",
      },
      {
        time: "17:00",
        temperature: 17,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "partlyCloudy",
      },
      {
        time: "18:00",
        temperature: 16,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
      {
        time: "19:00",
        temperature: 15,
        precipitationProbability: 20,
        precipitationMm: 0.1,
        windSpeedKmh: 8,
        weatherType: "cloudy",
      },
      {
        time: "20:00",
        temperature: 14,
        precipitationProbability: 20,
        precipitationMm: 0.1,
        windSpeedKmh: 8,
        weatherType: "cloudy",
      },
      {
        time: "21:00",
        temperature: 14,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "partlyCloudy",
      },
      {
        time: "22:00",
        temperature: 13,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "partlyCloudy",
      },
      {
        time: "23:00",
        temperature: 13,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "partlyCloudy",
      },
    ],
  },

  {
    date: "2026-09-21",
    dayName: "Mån",
    weatherType: "heavyRain",
    temperatureMax: 14,
    temperatureMin: 9,
    precipitationMm: 12.5,
    windSpeedKmh: 24,
    hourlyForecast: [
      {
        time: "00:00",
        temperature: 11,
        precipitationProbability: 70,
        precipitationMm: 0.8,
        windSpeedKmh: 19,
        weatherType: "rain",
      },
      {
        time: "01:00",
        temperature: 11,
        precipitationProbability: 75,
        precipitationMm: 1.0,
        windSpeedKmh: 20,
        weatherType: "rain",
      },
      {
        time: "02:00",
        temperature: 10,
        precipitationProbability: 80,
        precipitationMm: 1.1,
        windSpeedKmh: 21,
        weatherType: "heavyRain",
      },
      {
        time: "03:00",
        temperature: 10,
        precipitationProbability: 85,
        precipitationMm: 1.2,
        windSpeedKmh: 22,
        weatherType: "heavyRain",
      },
      {
        time: "04:00",
        temperature: 10,
        precipitationProbability: 90,
        precipitationMm: 1.3,
        windSpeedKmh: 23,
        weatherType: "heavyRain",
      },
      {
        time: "05:00",
        temperature: 9,
        precipitationProbability: 90,
        precipitationMm: 1.4,
        windSpeedKmh: 24,
        weatherType: "heavyRain",
      },
      {
        time: "06:00",
        temperature: 9,
        precipitationProbability: 90,
        precipitationMm: 1.5,
        windSpeedKmh: 24,
        weatherType: "heavyRain",
      },
      {
        time: "07:00",
        temperature: 10,
        precipitationProbability: 90,
        precipitationMm: 1.2,
        windSpeedKmh: 25,
        weatherType: "heavyRain",
      },
      {
        time: "08:00",
        temperature: 10,
        precipitationProbability: 85,
        precipitationMm: 1.0,
        windSpeedKmh: 25,
        weatherType: "heavyRain",
      },
      {
        time: "09:00",
        temperature: 11,
        precipitationProbability: 85,
        precipitationMm: 0.8,
        windSpeedKmh: 24,
        weatherType: "rain",
      },
      {
        time: "10:00",
        temperature: 12,
        precipitationProbability: 80,
        precipitationMm: 0.7,
        windSpeedKmh: 24,
        weatherType: "rain",
      },
      {
        time: "11:00",
        temperature: 12,
        precipitationProbability: 75,
        precipitationMm: 0.5,
        windSpeedKmh: 23,
        weatherType: "rain",
      },
      {
        time: "12:00",
        temperature: 13,
        precipitationProbability: 70,
        precipitationMm: 0.4,
        windSpeedKmh: 22,
        weatherType: "rain",
      },
      {
        time: "13:00",
        temperature: 13,
        precipitationProbability: 65,
        precipitationMm: 0.3,
        windSpeedKmh: 22,
        weatherType: "rain",
      },
      {
        time: "14:00",
        temperature: 14,
        precipitationProbability: 60,
        precipitationMm: 0.2,
        windSpeedKmh: 21,
        weatherType: "rain",
      },
      {
        time: "15:00",
        temperature: 14,
        precipitationProbability: 55,
        precipitationMm: 0.1,
        windSpeedKmh: 20,
        weatherType: "cloudy",
      },
      {
        time: "16:00",
        temperature: 13,
        precipitationProbability: 50,
        precipitationMm: 0.1,
        windSpeedKmh: 20,
        weatherType: "cloudy",
      },
      {
        time: "17:00",
        temperature: 13,
        precipitationProbability: 45,
        precipitationMm: 0,
        windSpeedKmh: 19,
        weatherType: "cloudy",
      },
      {
        time: "18:00",
        temperature: 12,
        precipitationProbability: 40,
        precipitationMm: 0,
        windSpeedKmh: 18,
        weatherType: "cloudy",
      },
      {
        time: "19:00",
        temperature: 12,
        precipitationProbability: 35,
        precipitationMm: 0,
        windSpeedKmh: 17,
        weatherType: "cloudy",
      },
      {
        time: "20:00",
        temperature: 11,
        precipitationProbability: 30,
        precipitationMm: 0,
        windSpeedKmh: 16,
        weatherType: "cloudy",
      },
      {
        time: "21:00",
        temperature: 11,
        precipitationProbability: 30,
        precipitationMm: 0,
        windSpeedKmh: 15,
        weatherType: "cloudy",
      },
      {
        time: "22:00",
        temperature: 10,
        precipitationProbability: 25,
        precipitationMm: 0,
        windSpeedKmh: 15,
        weatherType: "cloudy",
      },
      {
        time: "23:00",
        temperature: 10,
        precipitationProbability: 25,
        precipitationMm: 0,
        windSpeedKmh: 14,
        weatherType: "cloudy",
      },
    ],
  },

  {
    date: "2026-09-22",
    dayName: "Tis",
    weatherType: "clear",
    temperatureMax: 17,
    temperatureMin: 10,
    precipitationMm: 0,
    windSpeedKmh: 8,
    hourlyForecast: [
      {
        time: "00:00",
        temperature: 12,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "clear",
      },
      {
        time: "01:00",
        temperature: 12,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "clear",
      },
      {
        time: "02:00",
        temperature: 11,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 6,
        weatherType: "clear",
      },
      {
        time: "03:00",
        temperature: 11,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 6,
        weatherType: "clear",
      },
      {
        time: "04:00",
        temperature: 10,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 6,
        weatherType: "clear",
      },
      {
        time: "05:00",
        temperature: 10,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 6,
        weatherType: "clear",
      },
      {
        time: "06:00",
        temperature: 11,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "clear",
      },
      {
        time: "07:00",
        temperature: 12,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "clear",
      },
      {
        time: "08:00",
        temperature: 13,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "09:00",
        temperature: 14,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "10:00",
        temperature: 15,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "11:00",
        temperature: 16,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "clear",
      },
      {
        time: "12:00",
        temperature: 17,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "clear",
      },
      {
        time: "13:00",
        temperature: 17,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "clear",
      },
      {
        time: "14:00",
        temperature: 17,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "clear",
      },
      {
        time: "15:00",
        temperature: 16,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "16:00",
        temperature: 16,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "17:00",
        temperature: 15,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "clear",
      },
      {
        time: "18:00",
        temperature: 14,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "clear",
      },
      {
        time: "19:00",
        temperature: 13,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "clear",
      },
      {
        time: "20:00",
        temperature: 13,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 7,
        weatherType: "clear",
      },
      {
        time: "21:00",
        temperature: 12,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 6,
        weatherType: "clear",
      },
      {
        time: "22:00",
        temperature: 12,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 6,
        weatherType: "clear",
      },
      {
        time: "23:00",
        temperature: 11,
        precipitationProbability: 0,
        precipitationMm: 0,
        windSpeedKmh: 6,
        weatherType: "clear",
      },
    ],
  },

  {
    date: "2026-09-23",
    dayName: "Ons",
    weatherType: "partlyCloudy",
    temperatureMax: 20,
    temperatureMin: 13,
    precipitationMm: 0.6,
    windSpeedKmh: 11,
    hourlyForecast: [
      {
        time: "00:00",
        temperature: 14,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
      {
        time: "01:00",
        temperature: 14,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
      {
        time: "02:00",
        temperature: 13,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "cloudy",
      },
      {
        time: "03:00",
        temperature: 13,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "cloudy",
      },
      {
        time: "04:00",
        temperature: 13,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "cloudy",
      },
      {
        time: "05:00",
        temperature: 13,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "cloudy",
      },
      {
        time: "06:00",
        temperature: 14,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "partlyCloudy",
      },
      {
        time: "07:00",
        temperature: 15,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "partlyCloudy",
      },
      {
        time: "08:00",
        temperature: 16,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "partlyCloudy",
      },
      {
        time: "09:00",
        temperature: 17,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "partlyCloudy",
      },
      {
        time: "10:00",
        temperature: 18,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 11,
        weatherType: "partlyCloudy",
      },
      {
        time: "11:00",
        temperature: 19,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 11,
        weatherType: "partlyCloudy",
      },
      {
        time: "12:00",
        temperature: 20,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 12,
        weatherType: "partlyCloudy",
      },
      {
        time: "13:00",
        temperature: 20,
        precipitationProbability: 25,
        precipitationMm: 0.1,
        windSpeedKmh: 12,
        weatherType: "partlyCloudy",
      },
      {
        time: "14:00",
        temperature: 20,
        precipitationProbability: 25,
        precipitationMm: 0.1,
        windSpeedKmh: 12,
        weatherType: "cloudy",
      },
      {
        time: "15:00",
        temperature: 19,
        precipitationProbability: 30,
        precipitationMm: 0.1,
        windSpeedKmh: 11,
        weatherType: "cloudy",
      },
      {
        time: "16:00",
        temperature: 18,
        precipitationProbability: 30,
        precipitationMm: 0.1,
        windSpeedKmh: 11,
        weatherType: "cloudy",
      },
      {
        time: "17:00",
        temperature: 17,
        precipitationProbability: 25,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "partlyCloudy",
      },
      {
        time: "18:00",
        temperature: 16,
        precipitationProbability: 25,
        precipitationMm: 0,
        windSpeedKmh: 10,
        weatherType: "partlyCloudy",
      },
      {
        time: "19:00",
        temperature: 15,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "partlyCloudy",
      },
      {
        time: "20:00",
        temperature: 15,
        precipitationProbability: 20,
        precipitationMm: 0,
        windSpeedKmh: 9,
        weatherType: "partlyCloudy",
      },
      {
        time: "21:00",
        temperature: 14,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
      {
        time: "22:00",
        temperature: 14,
        precipitationProbability: 15,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
      {
        time: "23:00",
        temperature: 14,
        precipitationProbability: 10,
        precipitationMm: 0,
        windSpeedKmh: 8,
        weatherType: "partlyCloudy",
      },
    ],
  },
];
;
